import { JwtData, JwtHeader, JwtPayload } from './types';
import { decodePayload } from './utils/decode-payload';

/**
 * Returns the payload **without** verifying the integrity of the token. Please use `jwt.verify()` first to keep your application secure!
 *
 * @param {string} token The token string generated by `jwt.sign()`.
 * @returns {JwtData} Returns an `object` containing `header` and `payload`.
 */
export function decode(token: string): JwtData
{
    return {
        header : decodePayload(
            token.split('.')[0].replace(/-/g, '+').replace(/_/g, '/')
        ) as JwtHeader,
        payload: decodePayload(
            token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/')
        ) as JwtPayload,
    };
}